baseurl = "http://penguinpunch.com/"
title = "PenguinPUNCH Podcast"
copyright = "This site and content are licensed under the GPL, source code can be found [here](https://github.com/chasinglogic/penguinpunch.com)"
paginate = 9
languagecode = "en"

[taxonomies]
	category = "categories"

[params]
	author = [ "Mathew Robinson", "Justin Snyder", "Jason Crosby" ]
